import { Inter } from "next/font/google";
import "./globals.css";
import Al_Veshion_PersonalUseOnly from "../../public/fonts/Al_Veshion_PersonalUseOnly";
import Poppins_Regular from "../../public/fonts/Poppins_Regular";
import Exo_Regular from "../../public/fonts/Exo_Regular";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${Al_Veshion_PersonalUseOnly.variable} ${Poppins_Regular.variable} ${Exo_Regular.variable}`}
    >
      <body className={inter.className}>{children}</body>
    </html>
  );
}
